### PR TITLE
1. Implement Islandora child mappers

### PR DESCRIPTION
**Pull request by lthurston**
Things to discuss:

**caltech:** 

- How do we handle "restricted," which is basically a mechanism for skipping some records based on some condition? Might want to think about this holistically, solving the occasional need to skip some records based on conditions that are unique to the mapper.
- Not tested at all because Caltech endpoints are not working.

**sjsu:**

-  It does not modify its parent class. Does this seem right?

### CODE REVIEW

**Comment by lthurston** [comment]
[] Remove SJSU
[] Look into using Vernacular subclasses for the skipping mechanism mentioned above

**Comment by lthurston** [comment]
This is still a work in progress, but I've removed SJSU, and have implemented an extremely basic skipping mechanism.

**Comment by lthurston** [comment]
This still needs to be tested, and compared with Solr once the caltech endpoints are working.

**Comment by lthurston** [comment]
@amywieliczka @barbarahui There are only a couple mappers after the others got voted off the island: burbank and chs. They're working and this PR is ready for review.

**Review by amywieliczka — APPROVED** [review]

**Comment by lthurston** [comment]
@amywieliczka Had a merge conflict that I rebased out, so I need another approval. Sorry!

**Review by amywieliczka — APPROVED** [review]

**Comment by amywieliczka** [comment]
@lthurston should be all set.

**Pull request merged**
