### PR TITLE
CCA Vault Validator ID Workaround

### PR DESCRIPTION
**Pull request by amywieliczka**
@lthurston The TL;DR is that Calisphere IDs are complicated, but should you choose to run the CCA Vault validation locally, you should create a new working branch that merges this branch into any CCA Vault mapper refinements before running the validator in order to effectively compare legacy records with new records. 

------------------------------------------------------------------------------------------

And here's the long explanation of why 🔥Identifiers Are Complicated🔥 😱🤯🥵😮‍💨😵‍💫 

This is likely a meeting discussion at some point @bibliotechy and @barbarahui. I think we're unblocked on evaluating CIC's work for now though, and developing some Airflow tasks feels like the current pressing priority, so I'm leaving some super thorough notes here so we can pick it up later. Major thanks to @christinklez for catching this! 

------------------------------------------------------------------------------------------

The CCA Vault mapper is used for mapping [4 different collections](https://registry.cdlib.org/api/v1/rikoltifetcher/?format=json&mapper_type=cca_vault_oai_dc&ready_for_publication=true): 

- `3433`: [CCA/C Archives](https://calisphere.org/collections/3433/) - 492 items in Calisphere
- `3767`: [Capp Street Project Archive](https://calisphere.org/collections/3767/) - 69 items in Calisphere
- `26391`: [Artists' Books](https://calisphere.org/collections/26391/) - 1 item in Calisphere
- `26470`: [Hamaguchi Study Print Collection](https://calisphere.org/collections/26470/) - 790 items in Calisphere

Since `3767`, `26391`, and `26470` were last harvested to Calisphere, the underlying system ID (aka "Couch ID") has drifted. Collection `3433` seems to have been more recently re-harvested, so Calisphere has the "new version" system IDs for items in Collection `3433`. 

For example, let's take a look at the one item in `26391`:

| Couch ID | Calisphere ID |
| -------------|---------------|
| [`26391--oai:cca:17c06cc5-c419-4e77-9bdb-43c69e94b4cd/1`](https://harvest-stg.cdlib.org/couchdb/_utils/document.html?ucldc/26391--oai%3Acca%3A17c06cc5-c419-4e77-9bdb-43c69e94b4cd%2F1) | [`b18141c00b32b3daf476dbd591f4ebda`](https://calisphere.org/item/b18141c00b32b3daf476dbd591f4ebda/) |

Let's also take a look at an item from `3433`:

| Couch ID | Calisphere ID |
|-------------|---------------|
| [`3433--oai:vault.cca.edu:48da210f-7b65-416c-bbce-534f9c26e71d/1`](https://harvest-stg.cdlib.org/couchdb/_utils/document.html?ucldc/3433--oai%3Avault.cca.edu%3A48da210f-7b65-416c-bbce-534f9c26e71d%2F1) | [`1121aa2a86e4ada41ee84b481e2ef2e4`](https://calisphere.org/item/1121aa2a86e4ada41ee84b481e2ef2e4/) |

The old-style Couch IDs for the items from `3767`, `26391`, and `26470` include the prefix `oai:cca:`. The new-style Couch IDs for the items from `3433` include the prefix: `oai:vault.cca.edu:`. In Rikolti, the system ID for all items freshly re-harvested have this new-style prefix: `oai:vault.cca.edu`. Let's take a look at that same item from `26391`:

| Rikolti System ID | Calisphere ID |
| -------------|---------------|
| `26391--oai:vault.cca.edu:17c06cc5-c419-4e77-9bdb-43c69e94b4cd/1` | `d033252a8385893bee7ad81ea314c403` |

We use this system ID to pair up metadata records from the legacy system and Rikolti for comparison. This PR fakes the Rikolti IDs in order to make the new-style IDs look like the old-style IDs for these three collections for the sake of finding a comparable record and producing a validation report on that record. This is a temporary fake for the sake of generating a validation report - the code here does not actually change the Rikolti system ID. Due to this temporary fake, we are able to compare records from our legacy system to the Rikolti system - the validation report for 26391 shows:

| Harvest ID | Level | Field | Description | Expected Value | Actual Value |
| --- | --- | --- | --- | --- | --- |
| 26391--oai:cca:17c06cc5-c419-4e77-9bdb-43c69e94b4cd/1 | ERROR | Content mismatch | id | b18141c00b32b3daf476dbd591f4ebda | d033252a8385893bee7ad81ea314c403 |
| 26391--oai:cca:17c06cc5-c419-4e77-9bdb-43c69e94b4cd/1 | ERROR | Content mismatch | title | ['Crystals to Aden / Michel Bulteau ; translated by Pierre Joris'] | ['Crystals to Aden / Michel Bulteau ; translated by Pierre Joris.'] |
| 26391--oai:cca:17c06cc5-c419-4e77-9bdb-43c69e94b4cd/1 | ERROR | Required field is false, null, or empty | is_shown_by | https://vault.cca.edu/thumbs/17c06cc5-c419-4e77-9bdb-43c69e94b4cd/0/?gallery=preview | None |
| 26391--oai:cca:17c06cc5-c419-4e77-9bdb-43c69e94b4cd/1 | ERROR | Content mismatch | is_shown_by | https://vault.cca.edu/thumbs/17c06cc5-c419-4e77-9bdb-43c69e94b4cd/0/?gallery=preview | None |

We also use this system ID to generate the Calisphere ID. Since this PR fakes the Rikolti system IDs, but does not actually change the Rikolti system IDs, the Calisphere ID - which is an md5 hash of the system ID - is a new Calisphere ID. Therefore, in the validation reports for these three collections, we see a content mismatch report for every item, because the new Calisphere ID (generated based on the new-style system ID) does not match the old Calisphere ID (generated based on the old-style system ID). 

While this PR results in some noisy validation output (at least 1 line per record), it also unblocks us from otherwise evaluating the CCA Vault mapper for how it handles mapping all the other fields except this system ID and the Calisphere ID. 

Regarding the system ID and the Calisphere ID, we have a decision to make. I can see a number of solutions:
1) We re-harvest these collections now using the legacy system, and use the legacy system for managing the Calisphere ID redirects
2) We create a system for managing Calisphere ID redirects that will go into place with Rikolti
3) We modify the underlying system ID for these collections, rather than just faking it, so these Calisphere IDs remain the same as we move onto Rikolti
4) We take a hard look at Calisphere ID production in general, attempt to stabilize the Calisphere identifier space, remove the coupling of system ID to Calisphere ID, and create some tooling (and additional operator steps) to match up and modify re-harvested records to existing records, so identifiers are maintained at the record-level through re-harvest operations (rather than as a slew of redirects). 
5) We decide that persistent identifiers of Calisphere objects is not within Calisphere's scope of service? That seems bad. 

I did not see any entries in our existing redirect table for Collection 3433 - either it is a newer collection that was only harvested with the new style system IDs, or it was previously harvested and the old Calisphere IDs are lost (and any links pointing to those old Calisphere IDs are dead links now).

### CODE REVIEW

**Comment by christinklez** [comment]
See: [#3433](https://docs.google.com/spreadsheets/d/1nW63pR5bakrKkHDgD7xzEYr-cq4cFlUn74DGH5jwt5M/edit#gid=252656704) (08-09); [#3767](https://docs.google.com/spreadsheets/d/1PyFjlIrSD18Dex-1xKvtdtURCac6mcg_Gg9iI4KlDek/edit#gid=2140490545) (08-07); #[26470](https://docs.google.com/spreadsheets/d/1vGBm4jATmuKxeDEglHoLr5O0fn7gqMIfz5YAMp-KqnA/edit#gid=1127624953) (08-07); #[26391](https://docs.google.com/spreadsheets/d/1QBgqvfo7SUEjd139k3QNlOhs_B8do4uggjOWHipLVUA/edit#gid=1054262356) (08-07)

- **language**: Legacy record has a value but Rikolti record does not; vernacular data is fetching "eng". This is likely an enrichment (See examples in #3433, #3767, #26470) and also involves mapping.
- **is_shown_by**: Rikolti does not have is_shown_by links. Map is_shown_by. (All collections)
- **coverage / spatial**: List items are being mapped as a string; they should be kept as distinct list items. Map as distinct list items. (See examples in #3433)
- **format / creator / contributor / title:** trailing blank spaces at the end of some values; resulting in many false discrepancies. Able to clean up in the mapping or as an enrichment? Amy notes that existing enrichments should handle this; Lucas would you be able to decipher why this is happening. (See examples in #3433)

**Comment by lthurston** [comment]
> * **language**: Legacy record has a value but Rikolti record does not; vernacular data is fetching "eng". This is likely an enrichment (See examples in #3433, #3767, #26470) and also involves mapping.

Fixed. It is possible that the change to the mapping that I've made for CCA Vault is applicable to all OAI mappers, but we should probably hold off until we see that this is an issue for some other OAI mappers, lest we introduce a more issues than we solve.

> * **is_shown_by**: Rikolti does not have is_shown_by links. Map is_shown_by. (All collections)

Fixed.

> * **coverage / spatial**: List items are being mapped as a string; they should be kept as distinct list items. Map as distinct list items. (See examples in #3433)

This is the result of an enrichment. See 

```
"/shred?prop=sourceResource%2Fspatial&delim=--"
```

 on https://registry.cdlib.org/api/v1/rikolticollection/3433/?format=json.

This requires a change to the enrichments for this collection.

> * **format / creator / contributor / title:** trailing blank spaces at the end of some values; resulting in many false discrepancies. Able to clean up in the mapping or as an enrichment? Amy notes that existing enrichments should handle this; Lucas would you be able to decipher why this is happening. (See examples in #3433)

These extra spaces are in the source metadata. To resolve this -- it's one way to do it -- I've written a function in `OaiVernacular` called `strip_metadata()`, which strips whitespace off of string and list metadata values.

**Comment by lthurston** [comment]
Note: this branch is on top of the UCD branch because it has fixes for the Docker dev env post-module refactor.

**Comment by christinklez** [comment]
Adding one more request (missed this one as it didn't appear in the validation report, but spotted while eyeballing between records):
- source: map source. (This appears in the vernacular, but is not getting mapped.)

**Comment by lthurston** [comment]
> Adding one more request (missed this one as it didn't appear in the validation report, but spotted while eyeballing between records):
> 
> * source: map source. (This appears in the vernacular, but is not getting mapped.)

Fixed!

**Comment by amywieliczka** [comment]
Hey @lthurston, can you please remove the UCD fetcher and mapper commits from this PR? I understand that branch includes work that fixes your docker environment, but perhaps you could cherry pick those fixes into a branch that exclusively addresses those issues? I could pretty quickly and easily review and approve that work.

**Comment by lthurston** [comment]
> can you please remove the UCD fetcher and mapper commits from this PR?

Done.

**Comment by christinklez** [comment]
Hi @lthurston ! Thanks for addressing the previously reported issues. We reviewed the latest set of reports and are observing a couple of new things. We're noticing some characters in the mapped data that's not present in the source OAI data, so we're wondering if there is possibly an enrichment (or something happening in the mapping) that is introducing new characters. Would you be able to investigate where in the process these characters might be getting introduced? Perhaps this is something we can also discuss in a future check-in.

See: #3433 ([09-20](https://docs.google.com/spreadsheets/d/12gkrpNcT8d0bqZCm62qdpp_5j-_pyFojcsUM__2bLE0/edit#gid=902250647)); #3767 ([09-20](https://docs.google.com/spreadsheets/d/1JnBV9H58iH4RO2S8up1EoSk5MY7xwCXaW-dcHyj-7r4/edit#gid=1342529064)); #26470 ([09-20](https://docs.google.com/spreadsheets/d/1h3FutQsKfJe14uMP-V1kAiFBiEwkUf8OlsdF2oHK3Ik/edit#gid=450925389))

- **title** / **format** / **creator** / (& possibly **contributor**): extra (double) spaces are in the middle of a given line of text. See example in #3433, including the source OAI data in line 178 (there are no extra spaces in the OAI data; but there is an extra space in the mapped Rikolti data). Is this an enrichment error? (new issue observed in the 2023-09-20 validation report) -- (Note that in #3767 and #26470, we only observed this extra-spacing in **format**)

- **description**: `/n/n` characters appearing mid-paragraph in the validation report. See example in #3433, including the source OAI data in line 19 (there are `/n/n `in both the legacy and Rikolti data, but not in the source OAI data.) However, oddly, we don't see any `/n` characters in either the vernacular or the mapped metadata, so we're unsure if this is even an issue that needs fixing. Would you be able to investigate where this is occurring? And if this is, in fact, mapping `/n`'s, would you also be able to investigate cleaning this up either in the mapping or enrichment process? (this is also a new issue observed in the 2023-09-20 validation report) -- (Note that we only observed this issue in #3433)

**Comment by lthurston** [comment]
> * **title** / **format** / **creator** / (& possibly **contributor**): extra (double) spaces are in the middle of a given line of text. See example in #3433, including the source OAI data in line 178 (there are no extra spaces in the OAI data; but there is an extra space in the mapped Rikolti data). Is this an enrichment error? (new issue observed in the 2023-09-20 validation report) -- (Note that in #3767 and #26470, we only observed this extra-spacing in **format**)

The extra space is in the fetched data: 

3433: `<dc:title>Border/Fracture: Culture Change and Resistance under the Narcotraffic Regime, March 11,  2016</dc:title>`

3767: `<dc:format>22 color slides (2 x 2 in.) ; 2 color transparencies (4 x 5 in.) ;  15 black and white photographic prints (8 x 10 in.) ; 40 black and white photographic prints ;</dc:format>`

26470: `<dc:format>1 print; 30  x 20 in.</dc:format>`

**Comment by lthurston** [comment]
> * **description**: `\n\n` characters appearing mid-paragraph in the validation report. See example in #3433, including the source OAI data in line 19 (there are `\n\n `in both the legacy and Rikolti data, but not in the source OAI data.) ~However, oddly, we don't see any `\n` characters in either the vernacular or the mapped metadata, so we're unsure if this is even an issue that needs fixing.~ [Updating to add that the `\n`'s do in fact appear in the mapped metadata; I searched the wrong slash. They are not in the OAI or vernacular data.] Would you be able to investigate where this is being introduced and clean up either in the mapping or enrichment process? (This is also a new issue observed in the 2023-09-20 validation report) -- (Note that we only observed this issue in #3433)

In the source data, the linefeeds are present as a linebreak. It sounds like at some point in the mapping process they're getting escaped, becoming `\n`.

Here's what the source data looks like:

```
<dc:description>In fall of 2013 Eduardo Pineda's ENGAGE: Mural Arts class created murals for the Center for Elder’s Independence (CEI), a high quality, affordable integrated health care services program that promotes autonomy, quality of life and the ability of individuals to live in their communities. With guidance from CEI staff, students visited the Eastmont Town Center and the Josie Barrow Center to interview seniors over meals and hands-on activities and developed themes and imagery for the murals. The students designed and painted eight mural panels for the two facilities in which seniors attend day programs.  

Themes of nature, water, flight, day, night, and twilight are evocative settings used in the the mural designs to spark imagination. The fullness of life experience, the journeys taken, and the unique paths individuals chose are also expressed in the class murals, with an emphasis on introspection, togetherness, and joyful reunion.

</dc:description>
```

I'll figure out where this is happening.

**Comment by christinklez** [comment]
@amywieliczka @barbarahui -- we've reviewed the CCA Vault validation reports and declare the reports are valid! 🎉

**Pull request merged**
